#!/usr/bin/env bash

docker build -t tadpole-tutoring .
docker stop tadpole-tutoring
docker run --rm -d -p 80:80 --name tadpole-tutoring -v ~/tadpole-tutoring/index.db:/usr/src/app/index.db tadpole-tutoring 
